import XCTest
@testable import Skillego

/// Replays scripts/gen-ios-fixtures.js's fixtures — generated by running the
/// exact same rules.js file through Node's `vm` module — through the real,
/// bundled JSContext this app ships. This validates the actual loading/
/// marshaling pipeline (bundled files + bridge.js + JSON round-trip), not just
/// that the algorithm is right in the abstract.
final class JSEngineTests: XCTestCase {
    private var host: JSContextHost!

    override func setUp() {
        super.setUp()
        host = JSContextHost()
    }

    func testFixtures() async throws {
        // Xcode's default (non-folder-reference) resource copy flattens
        // SkillegoTests/Fixtures/*.json into the test bundle's root — enumerate
        // by extension rather than assuming a Fixtures/ subdirectory survives.
        let files = try XCTUnwrap(Bundle(for: Self.self).urls(forResourcesWithExtension: "json", subdirectory: nil))
            .sorted { $0.lastPathComponent < $1.lastPathComponent }
        XCTAssertFalse(files.isEmpty, "No fixtures found — run `node scripts/gen-ios-fixtures.js` first")

        for file in files {
            try await runFixture(at: file)
        }
    }

    private func runFixture(at url: URL) async throws {
        let data = try Data(contentsOf: url)
        guard let root = try JSONSerialization.jsonObject(with: data) as? [String: Any],
              let name = root["name"] as? String,
              let function = root["function"] as? String,
              let args = root["args"] as? [String: Any],
              let output = root["output"] else {
            XCTFail("\(url.lastPathComponent): malformed fixture")
            return
        }

        let inputData = try JSONSerialization.data(withJSONObject: root["input"] as Any)
        let input = try JSONDecoder().decode(FixtureInput.self, from: inputData)
        let loadPayload = try encode(makeLoadStatePayload(input))
        _ = try await host.call("ios_test_loadState", args: [loadPayload])

        let outputData = try JSONSerialization.data(withJSONObject: output)

        if function == "applyMoveToState" {
            let moveData = try JSONSerialization.data(withJSONObject: args["move"] as Any)
            let moveJSON = try XCTUnwrap(String(data: moveData, encoding: .utf8))
            let resultJSON = try await host.call("ios_test_applyMoveToState", args: [moveJSON])
            let actual = try decode(RawState.self, from: resultJSON)
            let expected = try JSONDecoder().decode(RawState.self, from: outputData)
            XCTAssertEqual(actual, expected, name)
        } else {
            let r = try XCTUnwrap(args["r"] as? Int)
            let c = try XCTUnwrap(args["c"] as? Int)
            let resultJSON = try await host.call(bridgeFunctionName(for: function), args: [String(r), String(c)])
            if function == "getValidMoves" {
                let actual = try decode([BoardCell].self, from: resultJSON)
                let expected = try JSONDecoder().decode([BoardCell].self, from: outputData)
                XCTAssertEqual(actual, expected, name)
            } else {
                let actual = try decode([GameMove].self, from: resultJSON)
                let expected = try JSONDecoder().decode([GameMove].self, from: outputData)
                XCTAssertEqual(actual, expected, name)
            }
        }
    }

    private func bridgeFunctionName(for function: String) -> String {
        "ios_" + function
    }
}

// MARK: - Fixture decoding

private struct FixturePiece: Decodable {
    var r: Int
    var c: Int
    var type: String
    var power: Int
    var player: Int
    var burning: Bool?
    var covered: Bool?
}

private struct FixtureInput: Decodable {
    var rows: Int
    var cols: Int
    var pieces: [FixturePiece]
    var pushBlocked: [BoardCell]
    var abilities: [String]
}

private struct TestLoadStatePayload: Encodable {
    var rows: Int
    var cols: Int
    var board: [[Piece?]]
    var covered: [[Bool]]
    var pushBlocked: [BoardCell]
    var abilities: [String]
}

private struct RawState: Decodable, Equatable {
    var board: [[Piece?]]
    var covered: [[Bool]]
    var pushBlocked: [BoardCell]
}

private func makeLoadStatePayload(_ input: FixtureInput) -> TestLoadStatePayload {
    var board = [[Piece?]](repeating: [Piece?](repeating: nil, count: input.cols), count: input.rows)
    var covered = [[Bool]](repeating: [Bool](repeating: false, count: input.cols), count: input.rows)
    for p in input.pieces {
        board[p.r][p.c] = Piece(type: p.type, power: p.power, player: p.player, burning: p.burning ?? false, quantity: nil, emoji: nil)
        if p.covered ?? false { covered[p.r][p.c] = true }
    }
    return TestLoadStatePayload(
        rows: input.rows, cols: input.cols, board: board, covered: covered,
        pushBlocked: input.pushBlocked, abilities: input.abilities
    )
}

private func encode(_ value: some Encodable) throws -> String {
    let data = try JSONEncoder().encode(value)
    return try XCTUnwrap(String(data: data, encoding: .utf8))
}

private func decode<T: Decodable>(_ type: T.Type, from json: String) throws -> T {
    let data = try XCTUnwrap(json.data(using: .utf8))
    return try JSONDecoder().decode(T.self, from: data)
}
